
version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile.app
    volumes:
      - .:/workspace
    ports:
      - "8080:8080" # Forward PostgreSQL port
    depends_on:
      - db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    develop:
      watch:
        - action: sync
          path: ./static
          target: /static
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./templates
  db:
    build:
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

